### PR TITLE
Use an intent label

### PR DESCRIPTION
**Pull request by larsgrefer**
This way the action can be translated way better.

### CODE REVIEW

**Comment by intrications** [comment]
Thanks!

**Comment by intrications** [comment]
@larsgrefer 

The build is now failing because Lint is complaining that this string now isn't translated into German:

<string name="intent_filter_label">Intercept the Intent</string>

Did you mean to add a translation? Or have I lost it during a manual merge?

**Comment by larsgrefer** [comment]
#28 should fix lint.

when i created the first german translation this string was not in master

**Comment by intrications** [comment]
Thanks for fix. I will push a new version to the Google Play Store.

**Comment by intrications** [comment]
@larsgrefer Thank you very much for the translation. You've inspired me to try to get translations for other languages: https://www.transifex.com/intrications/intent-intercept/

**Pull request merged**
