### PR TITLE
Extracted hardcoded Strings from

### PR DESCRIPTION
**Pull request by laurencemeynell**
Explode.java
    explode.xml
    SettingsUtil.java
into strings.xml

Strings with html tags were wrapped in <![CDATA[ ...html... ]]> tags and output as formatted text when you use Html.fromHtml(htmlString);

### CODE REVIEW

**Comment by laurencemeynell** [comment]
Oh dear, runs fine but I made lint angry adding a bunch of untranslated strings.  Not sure what the best approach is.  Don't want to unilaterally ignore lint warnings.

**Comment by intrications** [comment]
@laurencemeynell I will take a look.

In terms of the Html strings I think it would be better to style the text using Spans. Styling shouldn't really be part of the strings. A library like https://github.com/binaryfork/Spanny would make this simple. I am happy to make this change.

**Comment by laurencemeynell** [comment]
Thanks, that would be good.  It does seem more elegant doing it programmatically.

**Comment by intrications** [comment]
@laurencemeynell 

For now, don't worry about the Lint error. It'll go away once the translations are added for German. I'm sure there's a better way to deal with it but I'm not too worried since we know the cause of the error.

**Pull request merged**
